name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    name: Testing with Node version (${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [latest, 20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn quality:lint

      - name: Check circular dependencies
        run: yarn quality:circular-deps

      - name: Unit tests
        run: yarn quality:test

  e2e:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:25.0.0@sha256:008da4da0a285b9695d3bfdd1c5c5acb540ada14080d5b90269b34fdf4b9ec6a
      options: --user 1001

    services:
      database:
        image: postgres:18.1@sha256:5773fe724c49c42a7a9ca70202e11e1dff21fb7235b335a73f39297d200b73a2
        env:
          POSTGRES_DB: demo
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 'lts/iron'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: E2E tests
        uses: cypress-io/github-action@d0564b10b4b1b93309bc180754cc3cccb40844c7
        env:
          DATABASE_HOST: database
          DATABASE_PORT: 5432
          DATABASE_NAME: demo
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          IS_TEST: 1
        with:
          command: yarn quality:e2e:ci
          install: false
