name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn quality:lint

      - name: Check circular dependencies
        run: yarn quality:circular-deps

      - name: Unit tests
        run: yarn quality:test

  e2e:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:24.0.0@sha256:fe122441daa9ac524d5ea50da485f240fd2f037b3352fc4dfafe561cfc65cb18
      options: --user 1001
    needs: test

    services:
      database:
        image: postgres:17.5
        env:
          POSTGRES_DB: demo
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          package-manager-cache: false

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: E2E tests
        uses: cypress-io/github-action@6fc22051da87f9a2e6cf3d289d28f262bff0249c
        env:
          DATABASE_HOST: database
          DATABASE_PORT: 5432
          DATABASE_NAME: demo
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          IS_TEST: 1

        with:
          command: yarn quality:e2e:ci
          install: false

  publish:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    needs: [test, e2e]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Install npm latest version #needed for Trusted Publishing
        run: npm install -g npm@latest

      - name: Publish package to NPM
        run: npm publish --access public --provenance
