name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn quality:lint

      - name: Check circular dependencies
        run: yarn quality:circular-deps

      - name: Unit tests
        run: yarn quality:test

  e2e:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:25.0.0@sha256:008da4da0a285b9695d3bfdd1c5c5acb540ada14080d5b90269b34fdf4b9ec6a
      options: --user 1001
    needs: test

    services:
      database:
        image: postgres:18.0@sha256:41fc5342eefba6cc2ccda736aaf034bbbb7c3df0fdb81516eba1ba33f360162c
        env:
          POSTGRES_DB: demo
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 'lts/*'
          package-manager-cache: false

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: E2E tests
        uses: cypress-io/github-action@53299cbe789c64daab823c4bfb1882d05e9feaf3
        env:
          DATABASE_HOST: database
          DATABASE_PORT: 5432
          DATABASE_NAME: demo
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          IS_TEST: 1

        with:
          command: yarn quality:e2e:ci
          install: false

  publish:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    needs: [test, e2e]

    env:
      NPM_CONFIG_ACCESS: public
      NPM_CONFIG_PROVENANCE: true

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Install npm latest version #needed for Trusted Publishing
        run: npm install -g npm@latest

      - name: Publish package to NPM
        run: npm run publish -- from-git --yes
